name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build . -t public.ecr.aws/b2t3f0b4/projectrepo:latest

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws
          
      - name: Push Docker image to ECR
        run: docker push public.ecr.aws/b2t3f0b4/projectrepo:latest

      - name: Deploy to ECS
        run: |
          echo "Updating ECS service"
          aws ecs update-service --cluster arn:aws:ecs:ap-south-1:851725222812:cluster/ProjectCluster --service arn:aws:ecs:ap-south-1:851725222812:service/ProjectCluster/PTService --force-new-deployment
